### ISSUE TITLE
Plugin not working [Albert 0.24.3]

### ISSUE THREAD

**Issue by Noxis73** [hankliao87/albert-fd#1]
Thanks for your work. Unfortunately (at least in my case) it doesn't show up in the installed plugin list in albert. Albert get's lots of updates, maybe that's the reason?

Thanks in advance!
Kind regards

**Comment by hankhjliao** [comment]
Yes, the Python API changed a little bit.
I fixed the issue in 641ce826c8d086193442766456ed6b483a43a42a.

**Comment by Noxis73** [comment]
Thank you!
